# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SecretPlan < Formula
  desc "For secret value diff and save tool.(e.g aws secretsmanager)"
  homepage "https://github.com/yutachaos/secret-plan"
  version "0.0.32"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yutachaos/secret-plan/releases/download/v0.0.32/secret-plan_0.0.32_darwin_arm64.zip"
      sha256 "481ceaef8841e2c68dc130b6fba6dad116aeb954f29576ce75edfcdb54bf2ba8"

      def install
        bin.install Dir['secret-plan']
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yutachaos/secret-plan/releases/download/v0.0.32/secret-plan_0.0.32_darwin_amd64.zip"
      sha256 "595dceb56583d3ca605d79064d7580002fae5fd9fe412b81b8419314b86b4530"

      def install
        bin.install Dir['secret-plan']
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yutachaos/secret-plan/releases/download/v0.0.32/secret-plan_0.0.32_linux_arm64.zip"
      sha256 "44b560e1c6948ea7d1dc71e933cc7b0b44fd441b5bdcc892d695754a086c7e12"

      def install
        bin.install Dir['secret-plan']
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yutachaos/secret-plan/releases/download/v0.0.32/secret-plan_0.0.32_linux_amd64.zip"
      sha256 "724ba3aced2a84c78bb12f9782b109796bbc5e25043e47d1effb06d5dc3ccf45"

      def install
        bin.install Dir['secret-plan']
      end
    end
  end

  test do
    system "#{bin}/secret-plan"
  end
end
